name: Docker Image CI

on:
  push:
    branches: [ "tarefas" ]
  pull_request:
    branches: [ "tarefas" ]

  workflow_dispatch: 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Ze
      run: |
        ls -all
        echo zeeeeeeeeeeeeeeeeeeeeeee

