name: Docker Image CI

on:
  push:
    branches: [ "tarefas" ]
  pull_request:
    branches: [ "tarefas" ]

  workflow_dispatch: 
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: tarefas
        path: hello

    - name: Ze
      run: |
        ls -all
        ls -la hello
        cd hello
        docker build -t sergio24082026cr.azurecr.io/ze:v1
        docker login -u ${{secrets.ze}} -p ${{secrets.zepass}} sergio24082026cr.azurecr.io
        docker push sergio24082026cr.azurecr.io/ze:v1
        echo zeeeeeeeeeeeeeeeeeeeeeee

